### ISSUE TITLE
Game crashes upon pressing escape (in a level)

### ISSUE THREAD

**Issue by Geming400** [Alphalaneous/Pages-API#2]
There's litterally no stack trace so I can't really know what crashed my game
[2024-07-08_18-24-47.txt](https://github.com/user-attachments/files/16131986/2024-07-08_18-24-47.txt)

**Comment by Geming400** [comment]
Issue fixed

**Comment by auggeeo** [comment]
If the issue is fixed please close the issue @Geming400, or @Alphalaneous because i can't.

**Comment by Geming400** [comment]
I never closed an issue. My bad
